# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UV', models.CharField(max_length=10)),
                ('feelslike_f', models.IntegerField()),
                ('visibility_mi', models.IntegerField()),
                ('temp_f', models.CharField(max_length=6)),
                ('forecast_url', models.TextField()),
                ('weather', models.CharField(max_length=200)),
                ('relative_humidity', models.CharField(max_length=5)),
                ('pressure_in', models.CharField(max_length=10)),
                ('wind_dir', models.CharField(max_length=4)),
                ('wind_string', models.CharField(max_length=100)),
                ('wind_mph', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_forecast', models.DateTimeField()),
                ('day0_condition', models.TextField()),
                ('day0_high', models.CharField(max_length=5)),
                ('day0_low', models.CharField(max_length=5)),
                ('day0_prob', models.CharField(max_length=5)),
                ('day0_image', models.TextField()),
                ('day1_condition', models.TextField()),
                ('day1_high', models.CharField(max_length=5)),
                ('day1_low', models.CharField(max_length=5)),
                ('day1_prob', models.CharField(max_length=5)),
                ('day1_image', models.TextField()),
                ('day2_condition', models.TextField()),
                ('day2_high', models.CharField(max_length=5)),
                ('day2_low', models.CharField(max_length=5)),
                ('day2_prob', models.CharField(max_length=5)),
                ('day2_image', models.TextField()),
                ('day3_condition', models.TextField()),
                ('day3_high', models.CharField(max_length=5)),
                ('day3_low', models.CharField(max_length=5)),
                ('day3_prob', models.CharField(max_length=5)),
                ('day3_image', models.TextField()),
                ('day4_condition', models.TextField()),
                ('day4_high', models.CharField(max_length=5)),
                ('day4_low', models.CharField(max_length=5)),
                ('day4_prob', models.CharField(max_length=5)),
                ('day4_image', models.TextField()),
                ('day5_condition', models.TextField()),
                ('day5_high', models.CharField(max_length=5)),
                ('day5_low', models.CharField(max_length=5)),
                ('day5_prob', models.CharField(max_length=5)),
                ('day5_image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_request_time', models.DateTimeField()),
                ('request_zip', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sun',
            name='update_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.UpdateManager'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='update_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.UpdateManager'),
        ),
        migrations.AddField(
            model_name='currentconditions',
            name='update_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.UpdateManager'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='update_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.UpdateManager'),
        ),
    ]
